;;; GNU Guix --- Functional package management for GNU
;;; Copyright © 2023 Karl Hallsby <karl@hallsby.com>
;;;
;;; This file is part of GNU Guix.
;;;
;;; GNU Guix is free software; you can redistribute it and/or modify it
;;; under the terms of the GNU General Public License as published by
;;; the Free Software Foundation; either version 3 of the License, or (at
;;; your option) any later version.
;;;
;;; GNU Guix is distributed in the hope that it will be useful, but
;;; WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with GNU Guix.  If not, see <http://www.gnu.org/licenses/>.

(define-module (gnu services power)
  #:use-module (gnu packages power)
  #:use-module (gnu packages base)
  #:use-module (gnu packages mail)
  #:use-module (gnu services)
  #:use-module (gnu services shepherd)
  #:use-module (guix packages)
  #:use-module (guix build-system trivial)
  #:use-module (guix gexp)
  #:use-module (guix records)
  #:use-module (guix modules)
  #:use-module (srfi srfi-1)
  #:export (apcupsd-configuration
            apcupsd-service-type))

(define-record-type* <apcupsd-configuration>
  apcupsd-configuration make-apcupsd-configuration
  apcupsd-configuration?
  ;; file-like object
  (package apcupsd-configuration-package
           (default apcupsd))
  ;; boolean
  (auto-start? apcupsd-configuration-auto-start?
               (default #t))
  ;; string
  (ups-type apcupsd-configuration-ups-type
            (default "usb"))
  ;; string
  (ip-address apcupsd-configuration-ip-address
              (default "127.0.0.1"))
  ;; integer
  (battery-threshold apcupsd-configuration-battery-threshold
                     (default 50))
  ;; integer
  (minutes-threshold apcupsd-configuration-minutes-threshold
                     (default 5)))

(define (apcupsd-config-file config)
  "Return a list of configuration files for apcupsd based on the contents
of CONFIG."
  (mixed-text-file
   "apcupsd.conf"
   #~(begin
       (string-append
        "## apcupsd.conf v1.1 ##\n"
        ;; Taken from apcupsd nixos module
        "# apcupsd complains if the first line is not like above.\n"
        "# Generated by 'apcupsd-service'.\n"
        (string-append "UPSTYPE " #$(apcupsd-configuration-ups-type config) "\n")
        (string-append "NISIP " #$(apcupsd-configuration-ip-address config) "\n")
        (string-append "BATTERYLEVEL " #$(number->string (apcupsd-configuration-battery-threshold config)) "\n")
        (string-append "MINUTES " #$(number->string (apcupsd-configuration-minutes-threshold config)) "\n")))))

(define (apcupsd-shepherd-service config)
  "Return a list of <shepherd-service>s for apcupsd with CONFIG."

  (define package
    (apcupsd-configuration-package config))

  (define pid-file "/var/run/apcupsd.pid")

  (define config-file
    (apcupsd-config-file config))

  (define apcupsd-command
    #~(list (string-append #$package "/sbin/apcupsd")
            "-b" ;; Do not fork off to background
            "-P" #$pid-file
            "-f" #$(apcupsd-config-file config)
            "-d1"))

  (list (shepherd-service
         (documentation "apcupsd UPS monitoring daemon.")
         (requirement '(networking syslogd))
         (provision '(apcupsd))
         ;; Use make-inetd-constructor??
         (start #~(make-forkexec-constructor
                   #$apcupsd-command
                   #:pid-file #$pid-file
                   #:environment-variables
                   (list (string-append
                          "PATH="
                          #$(file-append package "/sbin") ":"
                          #$(file-append mailutils "/bin") ":"
                          #$(file-append coreutils "/bin")))))
         (stop #~(make-kill-destructor)))))

(define (apcupsd-wrapper config)
  "Wrap all the binaries in apcupsd to automatically pass the location
of the config file for the service."
  (define exp
    #~(begin
        ;; NOTE: sbin is the only one with ELF binaries. etc has SH scripts
        (let ((og-bins #$(file-append (apcupsd-configuration-package config)
                                      "/sbin/apctest")))
          (apply execl og-bins og-bins
                 "-f" #$(apcupsd-config-file config)
                 (cdr (command-line))))))

  (program-file "apctest-wrapped" exp))

(define (apcupsd-profile-service config)
  ;; XXX: profile-service-type only accepts <package> objects
  (list
   (package
     (name "apcupsd-wrapper")
     (version (package-version apcupsd))
     (source (apcupsd-wrapper config))
     (build-system trivial-build-system)
     (arguments
      '(#:modules ((guix build utils))
        #:builder
        (begin
          (use-modules (guix build utils))
          (let* ((source (assoc-ref %build-inputs "source"))
                 (out (assoc-ref %outputs "out"))
                 (sbin (string-append out "/sbin")))
            (mkdir-p sbin)
            (symlink source (string-append sbin "/apctest"))
            #t))))
     (home-page (package-home-page apcupsd))
     (synopsis (package-synopsis apcupsd))
     (description (package-description apcupsd))
     (license (package-license apcupsd)))))

(define (extend-apcupsd-configuration config extras)
  "Extend CONFIG with the extra EXTRAS."
  (apcupsd-configuration
   (inherit config)))

(define apcupsd-service-type
  (service-type (name 'apcupsd)
                (description
                 "Monitor APC UPSes using the apcupsd daemon, @command{apcupsd}.")
                (extensions
                 (list (service-extension shepherd-root-service-type
                                          apcupsd-shepherd-service)
                       ;; Install wrapped apcaccess & apctest in system profile
                       (service-extension profile-service-type
                                          apcupsd-profile-service)))
                (compose concatenate)
                (extend extend-apcupsd-configuration)
                (default-value (apcupsd-configuration))))
